title: MIT 6.S089
description: Course info and schedule for MIT 6.S089 - Intro to UI/UX Design
theme: just-the-docs

url: https://mituiux.github.io/

search_enabled: false

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
